### PR TITLE
Update UI test

### PR DESCRIPTION
**Pull request by trungleduc**

### CODE REVIEW

**Comment by jtpio** [comment]
Let's pin to an earlier version of `jupyterhub` for now?

Maybe it's worth opening an issue on the JupyterHub repo if https://github.com/jupyterhub/jupyterhub/pull/4750 is the change that breaks CI here?

**Comment by jtpio** [comment]
Looks like `nbgitpuller` is also having an issue with this upstream change: https://github.com/jupyterhub/nbgitpuller/issues/344

**Comment by trungleduc** [comment]
I want to spend a little bit of time to see if i can fix this before pinning jupyterhub

**Comment by jtpio** [comment]
Maybe https://github.com/jupyterhub/jupyterhub/pull/4759 will help.

**Comment by trungleduc** [comment]
I opened https://github.com/jupyterhub/jupyterhub/issues/4761

**Pull request closed without merging**
