### PR TITLE
Resolve 'Show Logs' issue by adding _xsrf token

### PR DESCRIPTION
**Pull request by yamaton**
Fix https://github.com/plasmabio/tljh-repo2docker/issues/60.

### CODE REVIEW

**Comment by pierrepo** [comment]
@jtpio would you mind review this PR?

**Comment by jtpio** [comment]
CI failure looks unrelated and likely due to the Notebook 7 release:

```
ERROR  - ModuleNotFoundError: No module named 'notebook.notebookapp'
```

**Comment by jtpio** [comment]
Merging the main branch to grab the CI fix from https://github.com/plasmabio/tljh-repo2docker/pull/62.

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
