### PR TITLE
Show the build logs in a dialog

### LINKED ISSUE #5: Follow the build logs
Similar to BinderHub, it would be useful to be able to follow the build logs after adding a new image:

image

We should look into reusing some parts of the BinderHub frontend, especially the one that uses `xterm.js` to display the logs. A couple of links:

- the [`BinderImage` abstraction](https://github.com/jupyterhub/binderhub/blob/23eeb4313d96890e3cc777e614135fa224da868c/binderhub/static/js/src/image.js#L3), that would hide implementation details such as the use of an `EventSource`
- [building a new `Terminal`](https://github.com/jupyterhub/binderhub/blob/23eeb4313d96890e3cc777e614135fa224da868c/binderhub/static/js/index.js#L228-L231) to show the logs

Also the build endpoint could follow the one from BinderHub and emit events.

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #5. 
Fixes https://github.com/plasmabio/plasma/issues/158.

### TODO

- [x] Add an endpoint to expose the build logs
- [x] Add a button to show the logs
- [x] Show the logs in a terminal in a dialog
- [x] Handle closed streams better (closed dialog) 
- [x] Add tests 
- [x] Add screenshot to the README

build-logs

### CODE REVIEW

**Comment by jtpio** [comment]
cc @pierrepo if you want to give it a try

**Comment by lachlancampbell** [comment]
Probably too early for me to comment, but I upgraded and tried to add a new environment, logs button was there, but no visible logs and environment still fails.
Screen Shot 2020-05-25 at 10 41 17 pm

**Comment by jtpio** [comment]
Thanks @lachlancampbell for trying it out!

Maybe it's an issue on the frontend. In that case it would be interesting to see if there is any error in the dev tools console? Maybe worth trying to clear the browser cache?

Otherwise, are you able to access the JupyterHub logs? https://docs.plasmabio.org/en/latest/troubleshooting/index.html#looking-at-logs

**Comment by lachlancampbell** [comment]
I can access the logs, what am I looking for? The jupyterhub logs show this error, looks like evry time I tried to show the build logs: /hub/api/environments/lachlancampbell-Bioinformatics:master/logs (106.68.4.34): No logs for image: lachlancampbell-Bioinformatics:master

**Comment by jtpio** [comment]
OK, it's probably because the generated name (from the github repo) is not lowercased (which is not valid for Docker).

Would it be possible to try with a custom name?

image

**Comment by lachlancampbell** [comment]
That did the trick, now just need to see if it builds :)

**Comment by jtpio** [comment]
Nice! I'll push a fix to handle this automatically.

**Comment by lachlancampbell** [comment]
Awesome, build completed successfully. I'll keep trying things, let you know if I run into anymore problems.

**Pull request merged**
