### PR TITLE
Add optional name to the environment

### LINKED ISSUE #6: Let user define image name
From 
- repository URL `https://github.com/plasmabio/template-python` 
- and reference `master`,

automatic name for Docker image is `plasmabio-template-python-master`. 

This is very efficient but not very informative for teachers and students.

Could we add a *Name* field in the environment creation form to let teacher input a more meaningful name? For instance, *2020-MEG-M1-UE1*

The *Name* field should be restricted to a given set of characters (A-Z, a-Z, 0-9, -)

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #6 

image

name-tooltip-2

### CODE REVIEW

**Comment by jtpio** [comment]
The regular expression might look a bit like random characters to the user at first glance, but at least it corresponds to the real regex used to validate the string.

**Comment by jtpio** [comment]
> Could you a placeholder for the _Name_ field? For instance `course-Python-101-B37` or something equivalent?

That can be useful indeed. Although the placeholder is not going to be the default value if left empty (while it is for the Reference).



> Is is possible to have a hint message to give more info on input fields? For instance for the _Name_ field a hint message could be "Name of the environment. Allowed characters are A to Z, a to z, 0 to 9, - and _"

I agree that the list of characters next to "Name" looks a bit odd actually. We can probably hide this in a tooltip.

**Comment by jtpio** [comment]
> We can probably hide this in a tooltip.

Or maybe just a message above / below the input field.

**Comment by jtpio** [comment]
With a tooltip:

name-tooltip

**Comment by pierrepo** [comment]
> That can be useful indeed. Although the placeholder is not going to be the default value if left empty (while it is for the Reference).

Oh yes. So it is probably NOT a good idea.

> Or maybe just a message above / below the input field.

Yes. Below sound great.
So we could add, below the *Name* input field something like "For instance, course-Python-101-B37 or 2020-MEG-M1-UE42"

Or tooltip could do the job too ;-)

**Comment by jtpio** [comment]
Something like this could be nice:

name-tooltip-2

**Pull request merged**
